name: Konnect - OAS conformance

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  lint-oas:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed oas files
        id: changed-oas-files
        uses: kong/changed-files@4edd678ac3f81e2dc578756871e4d00c19191daf
        with:
          files: |
            konnect/**/openapi.yaml

      - name: Setup decK
        if: steps.changed-oas-files.outputs.any_changed == 'true'
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.47.1'
          wrapper: false

      - name: Lint Spec files
        if: steps.changed-oas-files.outputs.any_changed == 'true'
        env:
          CHANGED_OAS_FILES: ${{ steps.changed-oas-files.outputs.all_changed_files }}
        run: |
          for FILE in ${CHANGED_OAS_FILES}; do
            deck file lint -s "$FILE" konnect/oas-file-rules.yaml
          done
