name: Konnect - koctl apply

on:
  workflow_dispatch:
  schedule:
    # Run apply every hour
    - cron: "0 * * * *"
  push:
    branches: [ main ]
    paths:
      - "konnect/teams.yaml"
      - "konnect/organizations.yaml"

jobs:
  koctl-apply:
    name: Apply configuration to Konnect 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup koctl
        uses: jaxxstorm/action-install-gh-release@v2.0.0
        with:
          repo: Kong/konnect-orchestrator

      - name: Run koctl apply
        id: koctl-apply
        env: 
          GITHUB_TOKEN: ${{ secrets.KONNECT_ORCHESTRATOR_GITHUB_TOKEN }}
          GITHUB_REPO_URL: "https://github.com/${{ github.repository }}"
        run: |
          koctl apply 
